// components/Overview/Kanban/dummyData.ts
import { Column, User, Tag } from "@/components/Overview/Kanban/types";

export const sampleUsers: User[] = [
  { id: "1", name: "John Doe", avatar: "JD", color: "bg-blue-500" },
  { id: "2", name: "Jane Smith", avatar: "JS", color: "bg-green-500" },
  { id: "3", name: "Mike Johnson", avatar: "MJ", color: "bg-red-500" },
  { id: "4", name: "Sarah Wilson", avatar: "SW", color: "bg-purple-500" },
  { id: "5", name: "Alex Brown", avatar: "AB", color: "bg-orange-500" },
  { id: "6", name: "Chris Davis", avatar: "CD", color: "bg-teal-500" },
  { id: "7", name: "Emma Taylor", avatar: "ET", color: "bg-pink-500" },
  { id: "8", name: "Olivia King", avatar: "OK", color: "bg-yellow-500" },
  { id: "9", name: "Liam Scott", avatar: "LS", color: "bg-indigo-500" },
  { id: "10", name: "Sophia Lee", avatar: "SL", color: "bg-cyan-500" },
];

export const sampleTags: Tag[] = [
  {
    id: "1",
    name: "Feature",
    color: "bg-blue-100 text-blue-700 border border-blue-200",
  },
  {
    id: "2",
    name: "Bug",
    color: "bg-red-100 text-red-700 border border-red-200",
  },
  {
    id: "3",
    name: "Frontend",
    color: "bg-purple-100 text-purple-700 border border-purple-200",
  },
  {
    id: "4",
    name: "Backend",
    color: "bg-green-100 text-green-700 border border-green-200",
  },
  {
    id: "5",
    name: "UX",
    color: "bg-orange-100 text-orange-700 border border-orange-200",
  },
  {
    id: "6",
    name: "Critical",
    color: "bg-red-200 text-red-800 border border-red-300",
  },
];

export const initialColumns: Column[] = [
  {
    id: "backlog",
    title: "Backlog",
    count: 6,
    color: "bg-white",
    dotColor: "bg-gray-400",
    tasks: [
      {
        id: "TASK-501",
        title: "Setup project repository",
        description: "Initialize Git repository and configure branches.",
        assignee: sampleUsers[0],
        comments: 1,
        attachments: 0,
        workItems: 10,
        tags: [sampleTags[0]],
        workItemType: "",
        startDate: "2025-09-01",
        endDate: "2025-09-05",
      },
      {
        id: "TASK-502",
        title: "Design landing page",
        description: "Create initial wireframes for the landing page.",
        assignee: sampleUsers[1],
        comments: 2,
        attachments: 1,
        workItems: 20,
        tags: [sampleTags[3], sampleTags[5]],
        workItemType: "",
        startDate: "2025-09-02",
        endDate: "2025-09-10",
      },
      {
        id: "TASK-503",
        title: "Add authentication endpoints",
        description: "Implement JWT login and signup APIs.",
        assignee: sampleUsers[2],
        comments: 0,
        attachments: 0,
        workItems: 15,
        tags: [sampleTags[0], sampleTags[4]],
        workItemType: "",
        startDate: "2025-09-03",
        endDate: "2025-09-12",
      },
      {
        id: "TASK-504",
        title: "Implement user profile",
        description: "Create user profile page with editable fields.",
        assignee: sampleUsers[3],
        comments: 3,
        attachments: 1,
        workItems: 25,
        tags: [sampleTags[2], sampleTags[4]],
        workItemType: "",
        startDate: "2025-09-05",
        endDate: "2025-09-20",
      },
      {
        id: "TASK-505",
        title: "Add dark mode toggle",
        description: "Implement dark mode toggle for all pages.",
        assignee: sampleUsers[4],
        comments: 1,
        attachments: 0,
        workItems: 12,
        tags: [sampleTags[0], sampleTags[4]],
        workItemType: "",
        startDate: "2025-09-06",
        endDate: "2025-09-18",
      },
      {
        id: "TASK-506",
        title: "Setup analytics tracking",
        description: "Integrate Google Analytics for all pages.",
        assignee: sampleUsers[5],
        comments: 2,
        attachments: 0,
        workItems: 18,
        tags: [sampleTags[0]],
        workItemType: "",
        startDate: "2025-09-07",
        endDate: "2025-09-21",
      },
    ],
  },
  {
    id: "progress",
    title: "In Progress",
    count: 6,
    color: "bg-white",
    dotColor: "bg-blue-500",
    tasks: [
      {
        id: "TASK-601",
        title: "Build dashboard widgets",
        description: "Create interactive dashboard widgets for key metrics.",
        assignee: sampleUsers[6],
        comments: 5,
        attachments: 2,
        workItems: 30,
        tags: [sampleTags[0], sampleTags[2]],
        workItemType: "",
        startDate: "2025-08-25",
        endDate: "2025-09-15",
      },
      {
        id: "TASK-602",
        title: "Fix date picker bug",
        description: "Date picker fails on Safari browsers.",
        assignee: sampleUsers[7],
        comments: 3,
        attachments: 0,
        workItems: 10,
        tags: [sampleTags[1]],
        workItemType: "",
        startDate: "2025-08-28",
        endDate: "2025-09-05",
      },
      {
        id: "TASK-603",
        title: "Integrate payment gateway",
        description: "Add Stripe integration for subscription payments.",
        assignee: sampleUsers[8],
        comments: 2,
        attachments: 1,
        workItems: 40,
        tags: [sampleTags[0], sampleTags[3]],
        workItemType: "",
        startDate: "2025-08-30",
        endDate: "2025-09-20",
      },
      {
        id: "TASK-604",
        title: "Implement notifications",
        description: "Add email and in-app notifications for users.",
        assignee: sampleUsers[9],
        comments: 4,
        attachments: 2,
        workItems: 25,
        tags: [sampleTags[3]],
        workItemType: "",
        startDate: "2025-08-29",
        endDate: "2025-09-18",
      },
      {
        id: "TASK-605",
        title: "Fix login redirect issue",
        description: "Some users are redirected incorrectly after login.",
        assignee: sampleUsers[0],
        comments: 1,
        attachments: 0,
        workItems: 12,
        tags: [sampleTags[1], sampleTags[5]],
        workItemType: "",
        startDate: "2025-08-31",
        endDate: "2025-09-07",
      },
      {
        id: "TASK-606",
        title: "API response caching",
        description: "Cache frequent API responses to reduce server load.",
        assignee: sampleUsers[1],
        comments: 2,
        attachments: 0,
        workItems: 20,
        tags: [sampleTags[3]],
        workItemType: "",
        startDate: "2025-08-27",
        endDate: "2025-09-17",
      },
    ],
  },
  {
    id: "review",
    title: "Review",
    count: 5,
    color: "bg-white",
    dotColor: "bg-purple-500",
    tasks: [
      {
        id: "TASK-701",
        title: "UI responsiveness audit",
        description: "Check UI components on multiple screen sizes.",
        assignee: sampleUsers[2],
        comments: 2,
        attachments: 0,
        workItems: 15,
        tags: [sampleTags[2], sampleTags[4]],
        workItemType: "",
        startDate: "2025-08-10",
        endDate: "2025-08-25",
      },
      {
        id: "TASK-702",
        title: "API endpoint testing",
        description: "Test all backend endpoints with Postman.",
        assignee: sampleUsers[3],
        comments: 3,
        attachments: 0,
        workItems: 20,
        tags: [sampleTags[3]],
        workItemType: "",
        startDate: "2025-08-05",
        endDate: "2025-08-20",
      },
      {
        id: "TASK-703",
        title: "Accessibility review",
        description: "Ensure all pages follow WCAG accessibility standards.",
        assignee: sampleUsers[4],
        comments: 1,
        attachments: 0,
        workItems: 10,
        tags: [sampleTags[4]],
        workItemType: "",
        startDate: "2025-08-08",
        endDate: "2025-08-22",
      },
      {
        id: "TASK-704",
        title: "Database index review",
        description: "Check indexes to optimize query performance.",
        assignee: sampleUsers[5],
        comments: 2,
        attachments: 0,
        workItems: 12,
        tags: [sampleTags[3]],
        workItemType: "",
        startDate: "2025-08-12",
        endDate: "2025-08-28",
      },
      {
        id: "TASK-705",
        title: "Security review",
        description: "Check all endpoints and frontend for security issues.",
        assignee: sampleUsers[6],
        comments: 3,
        attachments: 0,
        workItems: 18,
        tags: [sampleTags[1], sampleTags[5]],
        workItemType: "",
        startDate: "2025-08-15",
        endDate: "2025-08-30",
      },
    ],
  },
  {
    id: "completed",
    title: "Completed",
    count: 6,
    color: "bg-white",
    dotColor: "bg-green-500",
    tasks: [
      {
        id: "TASK-801",
        title: "Initial database setup",
        description: "Setup initial database schema and tables.",
        assignee: sampleUsers[0],
        comments: 0,
        attachments: 0,
        tags: [sampleTags[3]],
        completedDate: "2025-08-05",
        workItemType: "",
        startDate: "2025-07-20",
        endDate: "2025-07-30",
      },
      {
        id: "TASK-802",
        title: "Project plan creation",
        description: "Create overall project roadmap and milestones.",
        assignee: sampleUsers[1],
        comments: 1,
        attachments: 0,
        tags: [sampleTags[0]],
        completedDate: "2025-08-06",
        workItemType: "",
        startDate: "2025-07-22",
        endDate: "2025-07-28",
      },
      {
        id: "TASK-803",
        title: "Logo and branding design",
        description: "Design logo, color palette, and branding assets.",
        assignee: sampleUsers[2],
        comments: 2,
        attachments: 1,
        tags: [sampleTags[4]],
        completedDate: "2025-08-07",
        workItemType: "",
        startDate: "2025-07-23",
        endDate: "2025-07-30",
      },
      {
        id: "TASK-804",
        title: "Setup CI/CD pipeline",
        description: "Configure GitHub Actions for automated builds.",
        assignee: sampleUsers[3],
        comments: 0,
        attachments: 1,
        tags: [sampleTags[0]],
        completedDate: "2025-08-08",
        workItemType: "",
        startDate: "2025-07-25",
        endDate: "2025-08-02",
      },
      {
        id: "TASK-805",
        title: "Configure monitoring tools",
        description: "Setup Sentry and Datadog for error tracking.",
        assignee: sampleUsers[4],
        comments: 0,
        attachments: 0,
        tags: [sampleTags[3]],
        completedDate: "2025-08-09",
        workItemType: "",
        startDate: "2025-07-26",
        endDate: "2025-08-04",
      },
      {
        id: "TASK-806",
        title: "Initial front-end setup",
        description: "Setup React project with necessary dependencies.",
        assignee: sampleUsers[5],
        comments: 1,
        attachments: 0,
        tags: [sampleTags[2]],
        completedDate: "2025-08-10",
        workItemType: "",
        startDate: "2025-07-28",
        endDate: "2025-08-05",
      },
    ],
  },
];
